import { IncidentRecord, SmsRecord, IotNodeState } from "@/types/fire-detection";

export const initialIotNodes: IotNodeState[] = [
  {
    id: "NODE-01",
    name: "ESP32-CAM Unit Alpha",
    zone: "Server Room - Rack B & Power UPS",
    ipAddress: "192.168.1.142",
    isOnline: true,
    lastHeartbeat: "Just now (400ms ago)",
    esp32Temp: 38.6,
    wifiRssi: -58,
    cameraFps: 15.4,
    cameraResolution: "SVGA 800x600 (JPEG Stream)",
    flashLedActive: false,
    mq2Ppm: 685,
    mq2Threshold: 350,
    flameSensorDetected: true,
    buzzerActive: true,
    firmwareVersion: "ESP32-CAM-v2.4.1-RTOS",
  },
  {
    id: "NODE-02",
    name: "ESP32-CAM Unit Beta",
    zone: "Main Electronics Prototyping Lab",
    ipAddress: "192.168.1.143",
    isOnline: true,
    lastHeartbeat: "2s ago",
    esp32Temp: 34.1,
    wifiRssi: -64,
    cameraFps: 15.0,
    cameraResolution: "SVGA 800x600 (JPEG Stream)",
    flashLedActive: false,
    mq2Ppm: 142,
    mq2Threshold: 350,
    flameSensorDetected: false,
    buzzerActive: false,
    firmwareVersion: "ESP32-CAM-v2.4.1-RTOS",
  },
  {
    id: "NODE-03",
    name: "ESP32-CAM Unit Gamma",
    zone: "Chemical & Battery Storage Vault",
    ipAddress: "192.168.1.144",
    isOnline: true,
    lastHeartbeat: "4s ago",
    esp32Temp: 31.8,
    wifiRssi: -72,
    cameraFps: 14.8,
    cameraResolution: "SVGA 800x600 (JPEG Stream)",
    flashLedActive: false,
    mq2Ppm: 98,
    mq2Threshold: 350,
    flameSensorDetected: false,
    buzzerActive: false,
    firmwareVersion: "ESP32-CAM-v2.4.1-RTOS",
  },
];

export const initialIncidents: IncidentRecord[] = [
  {
    id: "INC-2026-1042",
    timestamp: "2026-10-07 15:42:12",
    nodeId: "NODE-01",
    nodeName: "ESP32-CAM Unit Alpha",
    location: "Server Room - Rack B & Power UPS",
    triggerType: "DUAL TRIGGER (FLAME + SMOKE)",
    gasPpm: 685,
    flameActive: true,
    severity: "CRITICAL",
    status: "PENDING VERIFICATION",
    snapshotUrl: "/esp32cam-fire.jpg",
    notes: "Both IR Flame Sensor (Pin GPIO 14) and MQ-2 Gas/Smoke (685 PPM vs 350 PPM threshold) tripped simultaneously. SMS broadcast dispatched to 4 contacts.",
    smsCount: 4,
  },
  {
    id: "INC-2026-1039",
    timestamp: "2026-10-07 11:15:04",
    nodeId: "NODE-02",
    nodeName: "ESP32-CAM Unit Beta",
    location: "Main Electronics Prototyping Lab",
    triggerType: "GAS/SMOKE SENSOR",
    gasPpm: 460,
    flameActive: false,
    severity: "WARNING",
    status: "FALSE ALARM",
    confirmedBy: "Engineer J. Akua",
    confirmedAt: "2026-10-07 11:16:22",
    snapshotUrl: "/esp32cam-normal.jpg",
    notes: "High rosin flux vapor from rework hot air station triggered MQ-2 threshold. Visual inspection confirmed no open flames or hazardous smoke.",
    smsCount: 2,
  },
  {
    id: "INC-2026-1035",
    timestamp: "2026-10-06 22:30:19",
    nodeId: "NODE-01",
    nodeName: "ESP32-CAM Unit Alpha",
    location: "Server Room - Rack B & Power UPS",
    triggerType: "FLAME SENSOR",
    gasPpm: 180,
    flameActive: true,
    severity: "ELEVATED",
    status: "FALSE ALARM",
    confirmedBy: "Duty Guard S. Miller",
    confirmedAt: "2026-10-06 22:32:05",
    snapshotUrl: "/esp32cam-normal.jpg",
    notes: "IR phototransistor reflected ambient flashlight beam during night security patrol inspection. Reset after live camera confirmatory view.",
    smsCount: 3,
  },
  {
    id: "INC-2026-1028",
    timestamp: "2026-10-04 14:08:44",
    nodeId: "NODE-03",
    nodeName: "ESP32-CAM Unit Gamma",
    location: "Chemical & Battery Storage Vault",
    triggerType: "DUAL TRIGGER (FLAME + SMOKE)",
    gasPpm: 720,
    flameActive: true,
    severity: "CRITICAL",
    status: "CONFIRMED FIRE",
    confirmedBy: "Fire Marshall Capt. Davis",
    confirmedAt: "2026-10-04 14:09:50",
    snapshotUrl: "/esp32cam-fire.jpg",
    notes: "Overheated LiFePO4 battery pack cell rupture. Visual confirmation verified flame flare; automatic halon suppression discharged and local fire station dispatched.",
    smsCount: 5,
  },
  {
    id: "INC-2026-1021",
    timestamp: "2026-10-02 09:44:11",
    nodeId: "NODE-02",
    nodeName: "ESP32-CAM Unit Beta",
    location: "Main Electronics Prototyping Lab",
    triggerType: "GAS/SMOKE SENSOR",
    gasPpm: 510,
    flameActive: false,
    severity: "WARNING",
    status: "RESOLVED",
    confirmedBy: "Lab Tech R. Owens",
    confirmedAt: "2026-10-02 09:47:30",
    snapshotUrl: "/esp32cam-normal.jpg",
    notes: "3D printer enclosure heating element scorch. Enclosure opened and ventilated, no flame progression.",
    smsCount: 2,
  },
  {
    id: "INC-2026-0994",
    timestamp: "2026-09-28 18:22:00",
    nodeId: "NODE-01",
    nodeName: "ESP32-CAM Unit Alpha",
    location: "Server Room - Rack B & Power UPS",
    triggerType: "GAS/SMOKE SENSOR",
    gasPpm: 395,
    flameActive: false,
    severity: "ELEVATED",
    status: "RESOLVED",
    confirmedBy: "Engineer J. Akua",
    confirmedAt: "2026-09-28 18:24:10",
    snapshotUrl: "/esp32cam-normal.jpg",
    notes: "Transient dust blown through HVAC duct during maintenance filter replacement. Level dropped below 150 PPM within 4 minutes.",
    smsCount: 2,
  },
];

export const initialSmsRecords: SmsRecord[] = [
  {
    id: "SMS-89410",
    incidentId: "INC-2026-1042",
    recipientName: "Captain Mark Davis",
    recipientPhone: "+1 (555) 019-2834",
    recipientRole: "Fire Department Liaison",
    timestamp: "2026-10-07 15:42:15",
    status: "DELIVERED",
    messageText: "[CRITICAL FIRE ALERT] IoT Node 01 detected FLAME (IR GPIO14) and SMOKE (685 PPM) at Server Room Rack B. Visual confirm immediately: https://pyrowatch.local/verify/INC-2026-1042",
    gateway: "SIM800L GSM (Cellular Quad-Band)",
    latencyMs: 1420,
  },
  {
    id: "SMS-89409",
    incidentId: "INC-2026-1042",
    recipientName: "Josephine Akua",
    recipientPhone: "+1 (555) 018-4721",
    recipientRole: "Facility Lead Engineer",
    timestamp: "2026-10-07 15:42:15",
    status: "DELIVERED",
    messageText: "[CRITICAL FIRE ALERT] IoT Node 01 detected FLAME (IR GPIO14) and SMOKE (685 PPM) at Server Room Rack B. Visual confirm immediately: https://pyrowatch.local/verify/INC-2026-1042",
    gateway: "SIM800L GSM (Cellular Quad-Band)",
    latencyMs: 980,
  },
  {
    id: "SMS-89408",
    incidentId: "INC-2026-1042",
    recipientName: "Building B Security Control",
    recipientPhone: "+1 (555) 014-9988",
    recipientRole: "24/7 Security Desk",
    timestamp: "2026-10-07 15:42:16",
    status: "DELIVERED",
    messageText: "[CRITICAL FIRE ALERT] IoT Node 01 detected FLAME (IR GPIO14) and SMOKE (685 PPM) at Server Room Rack B. Check video monitor & standby: https://pyrowatch.local/verify/INC-2026-1042",
    gateway: "Twilio Cloud SMS API (Backup Route)",
    latencyMs: 640,
  },
  {
    id: "SMS-89407",
    incidentId: "INC-2026-1042",
    recipientName: "IT Operations Duty Cell",
    recipientPhone: "+1 (555) 012-3456",
    recipientRole: "Infrastructure On-Call",
    timestamp: "2026-10-07 15:42:17",
    status: "DELIVERED",
    messageText: "[ALERT] Server Room thermal spike & smoke detected. Server automatic shutdown queued if fire confirmed: https://pyrowatch.local/verify/INC-2026-1042",
    gateway: "SIM800L GSM (Cellular Quad-Band)",
    latencyMs: 1850,
  },
  {
    id: "SMS-89375",
    incidentId: "INC-2026-1039",
    recipientName: "Josephine Akua",
    recipientPhone: "+1 (555) 018-4721",
    recipientRole: "Facility Lead Engineer",
    timestamp: "2026-10-07 11:15:08",
    status: "DELIVERED",
    messageText: "[SMOKE WARNING] Node 02 (Electronics Lab) MQ-2 sensor spiked to 460 PPM. No flame detected. Check live cam: https://pyrowatch.local/verify/INC-2026-1039",
    gateway: "SIM800L GSM (Cellular Quad-Band)",
    latencyMs: 1120,
  },
  {
    id: "SMS-89374",
    incidentId: "INC-2026-1039",
    recipientName: "Lab Safety Coordinator",
    recipientPhone: "+1 (555) 016-7721",
    recipientRole: "Lab Safety",
    timestamp: "2026-10-07 11:15:09",
    status: "DELIVERED",
    messageText: "[SMOKE WARNING] Node 02 (Electronics Lab) MQ-2 sensor spiked to 460 PPM. No flame detected. Check live cam: https://pyrowatch.local/verify/INC-2026-1039",
    gateway: "SIM800L GSM (Cellular Quad-Band)",
    latencyMs: 1340,
  },
  {
    id: "SMS-89352",
    incidentId: "INC-2026-1035",
    recipientName: "Duty Guard S. Miller",
    recipientPhone: "+1 (555) 015-8833",
    recipientRole: "Night Patrol Guard",
    timestamp: "2026-10-06 22:30:23",
    status: "DELIVERED",
    messageText: "[FLAME SENSOR TRIP] Node 01 optical IR sensor registered flame pulse. Smoke normal (180 PPM). Please visually verify: https://pyrowatch.local/verify/INC-2026-1035",
    gateway: "SIM800L GSM (Cellular Quad-Band)",
    latencyMs: 1210,
  },
  {
    id: "SMS-89351",
    incidentId: "INC-2026-1035",
    recipientName: "Josephine Akua",
    recipientPhone: "+1 (555) 018-4721",
    recipientRole: "Facility Lead Engineer",
    timestamp: "2026-10-06 22:30:24",
    status: "DELIVERED",
    messageText: "[FLAME SENSOR TRIP] Node 01 optical IR sensor registered flame pulse. Smoke normal (180 PPM). Please visually verify: https://pyrowatch.local/verify/INC-2026-1035",
    gateway: "SIM800L GSM (Cellular Quad-Band)",
    latencyMs: 1450,
  },
  {
    id: "SMS-89301",
    incidentId: "INC-2026-1028",
    recipientName: "Captain Mark Davis",
    recipientPhone: "+1 (555) 019-2834",
    recipientRole: "Fire Department Liaison",
    timestamp: "2026-10-04 14:08:48",
    status: "DELIVERED",
    messageText: "[CRITICAL FIRE ALERT] Node 03 (Chemical & Battery Storage) Flame detected + 720 PPM smoke! Visual confirmatory: https://pyrowatch.local/verify/INC-2026-1028",
    gateway: "SIM800L GSM (Cellular Quad-Band)",
    latencyMs: 890,
  },
  {
    id: "SMS-89300",
    incidentId: "INC-2026-1028",
    recipientName: "Emergency Services Dispatch 911",
    recipientPhone: "+1 (555) 011-9911",
    recipientRole: "Emergency Dispatch",
    timestamp: "2026-10-04 14:09:52",
    status: "DELIVERED",
    messageText: "[CONFIRMED INDUSTRIAL FIRE] Verified by Capt. Davis via ESP32-CAM visual inspection at Battery Storage Vault. Suppression system engaged. Responders required.",
    gateway: "Twilio Cloud SMS API (High Priority)",
    latencyMs: 420,
  },
];
